#!/usr/bin/env python2
import optparse
import sys
import bleu
from itertools import izip
from nltk.classify.naivebayes import NaiveBayesClassifier
from nltk.probability import UniformProbDist

optparser = optparse.OptionParser()
optparser.add_option("-k", "--kbest-list", dest="dev_input", default="data/dev.100best", help="100-best translation lists")
optparser.add_option("-r", "--reference-list", dest="dev_ref_input", default="data/dev.ref") 
optparser.add_option("-l", "--lm", dest="lm", default=-1.0, type="float", help="Language model weight")
optparser.add_option("-t", "--tm1", dest="tm1", default=-0.5, type="float", help="Translation model p(e|f) weight")
optparser.add_option("-s", "--tm2", dest="tm2", default=-0.5, type="float", help="Lexical translation model p_lex(f|e) weight")
(opts, _) = optparser.parse_args()
weights = {'p(e)'       : float(opts.lm) ,
           'p(e|f)'     : float(opts.tm1),
           'p_lex(f|e)' : float(opts.tm2)}

def rank_sort_key(f1, f2, c):
  d = {}
  for k in f1.keys():
    d[k] = f1[k] - f2[k]
  return c.classify(d)

all_refs = [s for s in open(opts.dev_ref_input)]
all_hyps = [pair.split(' ||| ') for pair in open(opts.dev_input)]
num_sents = len(all_hyps) / 100
training_instances = []
for s in xrange(0, num_sents):
#for s in xrange(0, 10):
  print >>sys.stderr, s
  ref = all_refs[s]
  hyps_for_one_sent = all_hyps[s * 100:s * 100 + 100]
  processed_hyps = []
  for (num, hyp, feats) in hyps_for_one_sent:
    feat_vec = {}
    for feat in feats.split(' '):
      (k, v) = feat.split('=')
      feat_vec[k] = float(v)
    bleu_stats = [x for x in bleu.bleu_stats(hyp, ref)]
    bleu_score = bleu.bleu(bleu_stats)
    processed_hyps.append((hyp, bleu_score, feat_vec))

  for i in xrange(len(processed_hyps)):
    (h1, b1, f1) = processed_hyps[i]
    for j in xrange(0, i):
      (h2, b2, f2) = processed_hyps[j]
      f = {}
      for k in f1.keys():
        f[k] = f1[k]-f2[k]
      h1_better = 1 if b1 > b2 else -1
      instance = (f, h1_better)
      training_instances.append(instance)

c = NaiveBayesClassifier.train(training_instances)

test_hyps = [pair.split(' ||| ') for pair in open("data/test.100best")]
test_refs = [r for r in open("data/test.ref")]
n = len(test_hyps)/100
for s in xrange(0, n):
  hyps_for_one_sent = test_hyps[s * 100:s * 100 + 100]
  hyps = []
  for (num, hyp, feats) in hyps_for_one_sent:
    feat_vec = {}
    for feat in feats.split(' '):
      (k, v) = feat.split('=')
      feat_vec[k] = float(v)
    hyps.append((hyp, feat_vec))

  best_list = sorted(hyps, reverse=True, cmp=(lambda (h1,f1),(h2,f2): rank_sort_key(f1,f2,c)))
  try: 
    (best, _) = best_list[0]
    sys.stdout.write("%s" % test_refs[s])
    sys.stdout.write("%s\n" % best)
  except (Exception):
    sys.exit(1)
