#!/usr/bin/env python2
import optparse
import sys
import bleu
from itertools import izip
from nltk.classify.naivebayes import NaiveBayesClassifier
from nltk.probability import UniformProbDist

optparser = optparse.OptionParser()
optparser.add_option("-k", "--kbest-list", dest="dev_input", default="data/dev.100best", help="100-best translation lists")
optparser.add_option("-r", "--reference-list", dest="dev_ref_input", default="data/dev.ref") 
optparser.add_option("-t", "--test-list", dest="test_input", default="data/test.100best") 
#optparser.add_option("-l", "--lm", dest="lm", default=-1.0, type="float", help="Language model weight")
#optparser.add_option("-t", "--tm1", dest="tm1", default=-0.5, type="float", help="Translation model p(e|f) weight")
#optparser.add_option("-s", "--tm2", dest="tm2", default=-0.5, type="float", help="Lexical translation model p_lex(f|e) weight")
(opts, _) = optparser.parse_args()
#weights = {'p(e)'       : float(opts.lm) ,
#           'p(e|f)'     : float(opts.tm1),
#           'p_lex(f|e)' : float(opts.tm2)}

def rank_sort_key(f1, f2, c):
  d = {}
  for k in f1.keys():
    d[k] = f1[k] - f2[k]
  return c.classify(d)

#from hw2
def compute_recall(hyp, ref):
  full_weight = 0.5
  trunc_weight = 0.5

  hwords = hyp.lower().split()
  rwords = ref.lower().split()
  hypset = set(hwords)
  refset = set(rwords)

  hwords_trunc = [word[:3] for word in hwords]
  rwords_trunc = [word[:3] for word in rwords]
  hypset_trunc = set(hwords_trunc)
  refset_trunc = set(rwords_trunc)

  recall = (sum(full_weight for word in refset if word in hypset) + \
              sum(trunc_weight for word in refset_trunc if word in hypset_trunc)) / len(refset)

  return recall

def create_base_feat_vec(hyp):
  f = {}
  f['len'] = len(hyp.split())
  return f

all_refs = [s for s in open(opts.dev_ref_input)]
all_hyps = [pair.split(' ||| ') for pair in open(opts.dev_input)]
num_sents = len(all_hyps) / 100
training_instances = []
for s in xrange(0, num_sents):
  print >>sys.stderr, s
  ref = all_refs[s]
  hyps_for_one_sent = all_hyps[s * 100:s * 100 + 100]
  processed_hyps = []
  for (num, hyp, feats) in hyps_for_one_sent:
    feat_vec = create_base_feat_vec(hyp)
    for feat in feats.split(' '):
      (k, v) = feat.split('=')
      feat_vec[k] = float(v)


    bleu_stats = [x for x in bleu.bleu_stats(hyp, ref)]
    l = 0.5
    score = l *bleu.bleu(bleu_stats)
    score += (1.0-l) * compute_recall(hyp, ref)
    processed_hyps.append((hyp, score, feat_vec))

  for i in xrange(len(processed_hyps)):
    (h1, b1, f1) = processed_hyps[i]
    for j in xrange(0, i):
      (h2, b2, f2) = processed_hyps[j]
      f = {}
      for k in f1.keys():
        f[k] = f1[k]-f2[k]
      h1_better = 1 if b1 > b2 else -1
      instance = (f, h1_better)
      training_instances.append(instance)

c = NaiveBayesClassifier.train(training_instances)

test_hyps = [pair.split(' ||| ') for pair in open(opts.test_input)]
n = len(test_hyps)/100
for s in xrange(0, n):
  hyps_for_one_sent = test_hyps[s * 100:s * 100 + 100]
  hyps = []
  for (num, hyp, feats) in hyps_for_one_sent:
    feat_vec = create_base_feat_vec(hyp)
    for feat in feats.split(' '):
      (k, v) = feat.split('=')
      feat_vec[k] = float(v)
    hyps.append((hyp, feat_vec))

  best_list = sorted(hyps, reverse=True, cmp=(lambda (h1,f1),(h2,f2): rank_sort_key(f1,f2,c)))
  try: 
    (best, _) = best_list[0]
    sys.stdout.write("%s\n" % best)
  except (Exception):
    sys.exit(1)
