#!/usr/bin/env python2
import optparse
import sys
import random
from collections import defaultdict

def uniform_0_1():
  return random.uniform(0, 1)

def em_iteration(t, opts, bitext):
  count = defaultdict(int)
  total = defaultdict(int)
  w_e_to_valid_w_f = defaultdict(set)

  for (n, (f, e)) in enumerate(bitext):
    for w_f in set(f):
      n_f = f.count(w_f)
      total_s = sum([t[(w_f, w_e)] * n_f for w_e in set(e)])
      for w_e in set(e):
        n_e = e.count(w_e)
        count[(w_f, w_e)] += t[(w_f, w_e)] * n_f * n_e / total_s
        total[w_e] += t[(w_f, w_e)] * n_f * n_e / total_s
        w_e_to_valid_w_f[w_e].add(w_f)

    if (n % 500 == 0):
      sys.stderr.write(".")

  sys.stderr.write("\nProcessed all sentences\n")
  for w_e in total.keys():
    for w_f in w_e_to_valid_w_f[w_e]:
      t[(w_f, w_e)] = count[(w_f, w_e)] / total[w_e]

def print_best_alignments(t, opts, bitext):
  for (f, e) in bitext:
    for (i, w_f) in enumerate(f):
      possible_alignments = [(j, t[(w_f, w_e)]) for (j, w_e) in enumerate(e) if (w_f, w_e) in t]
      (j, _) = max(possible_alignments, key=(lambda (j, p): p))
      sys.stdout.write("%i-%i " % (i, j))
    sys.stdout.write("\n")

if __name__ == '__main__':
  random.seed(4) #for consistency during testing...

  optparser = optparse.OptionParser()
  optparser.add_option("-b", "--bitext", dest="bitext", default="data/dev-test-train.de-en", \
                       help="Parallel corpus (default data/dev-test-train.de-en)")
  optparser.add_option("-i", "--iterations", dest="iterations", default=5, type="int", \
                       help="Number of EM iterations to perform (default=5)")
  optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", \
                       help="Number of sentences to use for training and alignment")
  (opts, _) = optparser.parse_args()

  t = defaultdict(uniform_0_1)
  bitext = [[sentence.strip().split() for sentence in pair.split(' ||| ')] for pair in open(opts.bitext)][:opts.num_sents]

  for i in range(opts.iterations):
    sys.stderr.write("On iteration %i\n" % i)
    em_iteration(t, opts, bitext)

  print_best_alignments(t, opts, bitext)
