#!/usr/bin/env python2

import argparse
import json
import os, sys, math, string

def extract_features(hyp, ref):
  alpha = 0.85
  full_weight = 1.0
  trunc_weight = 1.0

  hwords = hyp.lower().split(' -')
  rwords = ref.lower().split(' -')
  hypset = set(hwords)
  refset = set(rwords)

  hwords_trunc = [word[:6] for word in hwords]
  rwords_trunc = [word[:6] for word in rwords]
  hypset_trunc = set(hwords_trunc)
  refset_trunc = set(rwords_trunc)

  precision = (sum(full_weight for word in hwords if word in refset) + \
              sum(trunc_weight for word in hwords_trunc if word in refset_trunc)) / len(hwords)
  recall = (sum(full_weight for word in rwords if word in hypset) + \
              sum(trunc_weight for word in rwords_trunc if word in hypset_trunc)) / len(rwords)

  try:
    meteor = (precision*recall) / (alpha*precision + (1.0-alpha)*recall)
  except ZeroDivisionError:
    meteor = 0.0

  return {'meteor':meteor}

argparser = argparse.ArgumentParser(prog='extract')
argparser.add_argument('-x', '--pairs', dest='pairs', default='data/en-cs.pairs', help='Reference-Hypothesis pairs')

args = argparser.parse_args()

lc = 0
sys.stderr.write('Extracting features for (ref,hyp) pairs from %s.\n' % args.pairs)
# loop over all (ref,hyp) pairs in the input file and extract evaluation features
for ref_hyp in open(args.pairs):
  lc += 1
  ref, hyp = ref_hyp.rstrip().split(' ||| ')
  fmap = extract_features(hyp, ref)
  print json.dumps(fmap)   # print evaluation feature map

