#!/usr/bin/env python2

import argparse
import json
import os, sys, math, string

def extract_features(hyp, ref):
  recall = compute_recall(hyp, ref)
  exact = 1 if hyp == ref else 0
  return {'recall':recall, 'exact':exact}

def compute_recall(hyp, ref):
  full_weight = 0.5
  trunc_weight = 0.5
  #full_weight = float(args.full)
  #trunc_weight = float(args.trunc)

  hwords = hyp.lower().split()
  rwords = ref.lower().split()
  hypset = set(hwords)
  refset = set(rwords)

  hwords_trunc = [word[:3] for word in hwords]
  rwords_trunc = [word[:3] for word in rwords]
  hypset_trunc = set(hwords_trunc)
  refset_trunc = set(rwords_trunc)

  recall = (sum(full_weight for word in refset if word in hypset) + \
              sum(trunc_weight for word in refset_trunc if word in hypset_trunc)) / len(refset)

  return recall

argparser = argparse.ArgumentParser(prog='extract')
argparser.add_argument('-x', '--pairs', dest='pairs', default='data/en-cs.pairs', help='Reference-Hypothesis pairs')
argparser.add_argument('-f', dest='full')
argparser.add_argument('-t', dest='trunc')

args = argparser.parse_args()

lc = 0
sys.stderr.write('Extracting features for (ref,hyp) pairs from %s.\n' % args.pairs)
# loop over all (ref,hyp) pairs in the input file and extract evaluation features
for ref_hyp in open(args.pairs):
  lc += 1
  ref, hyp = ref_hyp.rstrip().split(' ||| ')
  fmap = extract_features(hyp, ref)
  print json.dumps(fmap)   # print evaluation feature map

